version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
region = "us-west-1"
confirm_changeset = true
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
disable_rollback = false
resolve_s3 = true
s3_prefix = "sam-app"
image_repositories = []